adding jenkins check & updated branch name

diff --git a/.github/workflows/plugin_update.yml b/.github/workflows/plugin_update.yml
--- a/.github/workflows/plugin_update.yml
+++ b/.github/workflows/plugin_update.yml
@@ -19,18 +19,31 @@ jobs:
           git config --global user.email "ash.191245141@gmail.com"
           git config --global user.name "ash-sxn"
 
-      - name: Check plugins
+      - name: Set branch Names and start the containers
         run: |
           # Set the name of the branch to create the pull request from
-          BRANCH_NAME="update-plugins"
+          BRANCH_NAME="update-plugins-$(date +'%Y/%m/%d/%H/%M/%S')"
 
           # Set the name of the branch to create the pull request to
-          BASE_BRANCH="main"
+          BASE_BRANCH="${GITHUB_REF#refs/heads/}"
           
           # Start the docker containers
           docker compose up -d 
-          # Uses jenkins-plugin-cli to update the plugin.txt and update it in root
-          docker ps | grep controller | awk '{print $1}' | xargs -I {} docker exec -u root {} jenkins-plugin-cli --plugin-file /usr/share/jenkins/ref/plugins.txt --no-download --available-updates --output txt > dockerfiles/plugins.txt
+
+
+      - name: Waiting for service to be ready
+        run: |
+          # Check If Jenkins is running or not
+          # If the message is found, awk exits with a non-zero status (1), and the loop continues.
+          # If the message is not found, the loop exits, and the "Jenkins is running" message is displayed.
+          timeout 60 bash -c 'until curl -s -f http://127.0.0.1:8080/login > /dev/null; do sleep 5; done' && echo "Jenkins is running" || echo "Jenkins is not running" && exit 1
+          echo "Jenkins is ready"
+          JENKINS_VERSION=$(curl -s -I -k http://admin:admin@127.0.0.1:8080 | grep -i '^X-Jenkins:' | awk '{print $2}')
+          echo "Jenkins version is: $JENKINS_VERSION"
+
+
+          # Uses jenkins-plugin-cli to update the plugin.txt and update it 
+          docker ps | grep controller | awk '{print $1}' | xargs -I {} docker exec {} jenkins-plugin-cli --plugin-file /usr/share/jenkins/ref/plugins.txt --no-download --available-updates --output txt > dockerfiles/plugins.txt
           # Check if the plugins.txt file has been modified
           if git diff --quiet -- dockerfiles/plugins.txt; then
               # No changes
